# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tfAIhIDqjNC6WAZlGL2Qe9re1I8CJt0G
"""

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

customer=pd.read_csv("/content/Customer-Churn-Records.csv")

customer.head()

customer.duplicated().sum()

customer.isna().sum()

customer.info()

customer.describe()

customer.drop("RowNumber",axis=1,inplace=True)

customer.drop("CustomerId",axis=1,inplace=True)

customer.drop(['Surname',"Geography","Gender","Gender","Card Type"],axis=1,inplace=True)

customer.head()

sns.heatmap(customer.corr())

X=customer.drop("Exited",axis=1)
y=customer["Exited"]
min_max=MinMaxScaler()
X=min_max.fit_transform(X)

x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)
model=LinearRegression()
model.fit(x_train,y_train)

predict=model.predict(x_test)

evaluate=model.score(x_test,y_test)
evaluate

train_score = model.score(x_train, y_train)
test_score = model.score(x_test, y_test)

print("Train Score:", train_score)
print("Test Score:", test_score)

from sklearn.linear_model import Lasso, Ridge
ridge = Ridge(alpha=0.1)
ridge.fit(x_train, y_train)

ridge_score=ridge.score(x_test, y_test)

lasso = Lasso(alpha=0.1)
lasso.fit(x_train, y_train)

lasso_score=lasso.score(x_test, y_test)

models = ['Linear', 'Ridge', 'Lasso']
scores = [test_score, ridge_score,lasso_score]

plt.figure(figsize=(8, 5))
plt.bar(models, scores, color=['blue', 'green', 'red'])
plt.ylim(0, 1.1)
plt.title('Model Comparison (R² Score)')
plt.ylabel('R² Score')
plt.xlabel('Model')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()